### ISSUE TITLE
非常好的项目，作者后续能否添加almost full/empty信号？

### ISSUE THREAD

**Issue by Taocheng99** [lauchinyuan/Asymmetric_async_FIFO#1]
非常好的项目，是目前找到的一个最方便使用的FWFT FIFO，已经在项目中使用。

**Comment by lauchinyuan** [comment]
> 非常好的项目，是目前找到的一个最方便使用的FWFT FIFO，已经在项目中使用。
感谢关注，等后续有空了来哈哈，先close。
